# Generated by Django 5.0.2 on 2024-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='norm',
            field=models.CharField(blank=True, help_text='Норма', max_length=20, verbose_name='норма'),
        ),
    ]
